# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@4.7
  aws-code-deploy: circleci/aws-code-deploy@2.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test --maxWorkers=2

workflows:
  build-and-test-deploy-workflow:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                main
      - aws-code-deploy/deploy:
          requires:
            - build-and-test
          application-name: muscleman
          bundle-bucket: muscleman-deploy
          deployment-group: web
          bundle-key: muscleman-zip
          service-role-arn: hyungseok
          filters:
            branches:
              only:
                main